"""add foreign keys to tickets

Revision ID: 87f1cb13781a
Revises: 08856e8bdfa5
Create Date: 2026-09-29 15:12:58.456395

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87f1cb13781a'
down_revision: str | Sequence[str] | None = '08856e8bdfa5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_tickets_assignee_id', 'tickets', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key('fk_tickets_requester_id', 'tickets', 'users', ['requester_id'], ['id'])
    op.create_foreign_key('fk_tickets_organization_id', 'tickets', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_tickets_organization_id', 'tickets', type_='foreignkey')
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_tickets_requester_id', 'tickets', type_='foreignkey')
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_tickets_assignee_id', 'tickets', type_='foreignkey')
    # ### end Alembic commands ###
